version: '3'

services:

  frontend:
    image: node
    volumes:
      - ./frontend:/code
    ports:
      - 8080:8080
    working_dir: /code/

  db:
    image: postgres:11
    ports:
      - 5432:5432
    networks:
      - bcros
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bcros
  
  search_api:
    image: search_api
    build:
      context: search-api
    ports:
      - 80:5000
    volumes:
      - ./search-api:/opt/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/opt/app
    networks:
      - bcros

networks:
  bcros:
    driver: "bridge"

volumes:
  postgres-data:
