version: '3'

services:

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code
    working_dir: /code/

  db:
    image: postgres:9.6
    networks:
      - bcros
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bcros
    environment:
      - POSTGRES_PASSWORD=password

  search_api:
    image: search_api
    build:
      context: search-api
    volumes:
      - ./search-api:/opt/app
      - ./instantclient:/opt/ora/instantclient
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/opt/app/src
      - ORACLE_HOME=/opt/ora/instantclient
    networks:
      - bcros

networks:
  bcros:
    driver: "bridge"

volumes:
  postgres-data:
