version: '3'

services:

  search-web:
    build: ./search-web
    volumes:
      - ./search-web:/code
    working_dir: /code/

  db:
    image: postgres:9.6
    networks:
      - bcros
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bcros
    environment:
      - POSTGRES_PASSWORD=password

  search-api:
    build:
      context: search-api
    volumes:
      - ./search-api:/opt/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - bcros

networks:
  bcros:
    driver: "bridge"

volumes:
  postgres-data:
