name: Search Web CHECK CI

on:
  push:
    branches:
      - master
    paths:
      - "search-web/**"
  pull_request:
    branches:
      - master
    paths:
      - "search-web/**"

jobs:
  search-web-check:
    runs-on: ubuntu-latest
    if: github.repository == 'countable-web/sbc-search'

    strategy:
      matrix:
        node: [ '13' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        working-directory: ./search-web
        run: |
          docker-compose build search-web
      - name: Run yarn tests
        working-directory: ./search-web
        run: |
          docker-compose run search-web yarn test:unit
      - name: Shutdown docker-compose
        working-directory: ./search-web
        run: |
          docker-compose down