name: Search web CI

on:
  pull_request:
    branches:
      - master
    paths:
      - "search-web/**"

jobs:
  search-web-ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./search-web

    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          make setup
        env:
          CI: true
      - name: Run Lint
        run: |
          make lint
        env:
          CI: true
      - name: Run Unit Tests
        run: |
          make test
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: codecov-search-web
          fail_ci_if_error: true
      - name: Run build
        run: |
          make build-nc
        env:
          CI: true
