"""empty message

Revision ID: 10ec817e65d0
Revises: e4d106926f51
Create Date: 2020-02-17 07:52:47.686042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ec817e65d0'
down_revision = 'e4d106926f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CORP_OP_STATE',
    sa.Column('state_typ_cd', sa.String(length=3), nullable=False),
    sa.Column('op_state_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('short_desc', sa.String(length=15), nullable=True),
    sa.Column('full_desc', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('state_typ_cd')
    )
    op.create_table('CORP_STATE',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('start_event_id', sa.Integer(), nullable=False),
    sa.Column('end_event_id', sa.Integer(), nullable=True),
    sa.Column('state_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('dd_corp_num', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('corp_num', 'start_event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CORP_STATE')
    op.drop_table('CORP_OP_STATE')
    # ### end Alembic commands ###
