'''empty message

Revision ID: 5d636cfe1a5e
Revises: f1714b3e3bfa
Create Date: 2020-04-24 19:38:36.010499

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d636cfe1a5e'
down_revision = 'f1714b3e3bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_type',
    sa.Column('party_typ_cd', sa.String(length=3), nullable=False),
    sa.Column('short_desc', sa.String(length=75), nullable=True),
    sa.Column('full_desc', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('party_typ_cd')
    )
    op.drop_table('office_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('office_type',
    sa.Column('office_typ_cd', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('short_desc', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('full_desc', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('office_typ_cd', name='office_type_pkey')
    )
    op.drop_table('party_type')
    # ### end Alembic commands ###
