"""initial

Revision ID: 64b51387b13b
Revises: 
Create Date: 2020-01-28 00:53:46.288130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b51387b13b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CORPORATION',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('corp_frozen_typ_cd', sa.String(length=1), nullable=True),
    sa.Column('corp_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('recognition_dts', sa.Date(), nullable=True),
    sa.Column('last_ar_filed_dt', sa.Date(), nullable=True),
    sa.Column('transition_dt', sa.Date(), nullable=True),
    sa.Column('bn_9', sa.String(length=9), nullable=True),
    sa.Column('bn_15', sa.String(length=15), nullable=True),
    sa.Column('accession_num', sa.String(length=10), nullable=True),
    sa.Column('CORP_PASSWORD', sa.String(length=300), nullable=True),
    sa.Column('PROMPT_QUESTION', sa.String(length=100), nullable=True),
    sa.Column('admin_email', sa.String(length=254), nullable=True),
    sa.Column('send_ar_ind', sa.String(length=1), nullable=True),
    sa.Column('tilma_involved_ind', sa.String(length=1), nullable=True),
    sa.Column('tilma_cessation_dt', sa.Date(), nullable=True),
    sa.Column('firm_last_image_date', sa.Date(), nullable=True),
    sa.Column('os_session', sa.Integer(), nullable=True),
    sa.Column('last_agm_date', sa.Date(), nullable=True),
    sa.Column('firm_lp_xp_termination_date', sa.Date(), nullable=True),
    sa.Column('last_ledger_dt', sa.Date(), nullable=True),
    sa.Column('ar_reminder_option', sa.String(length=10), nullable=True),
    sa.Column('ar_reminder_date', sa.String(length=20), nullable=True),
    sa.Column('TEMP_PASSWORD', sa.String(length=300), nullable=True),
    sa.Column('TEMP_PASSWORD_EXPIRY_DATE', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('corp_num'),
    sa.UniqueConstraint('corp_num')
    )
    op.create_table('CORP_PARTY',
    sa.Column('corp_party_id', sa.Integer(), nullable=False),
    sa.Column('mailing_addr_id', sa.Integer(), nullable=True),
    sa.Column('delivery_addr_id', sa.Integer(), nullable=True),
    sa.Column('corp_num', sa.String(length=10), nullable=True),
    sa.Column('party_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('start_event_id', sa.Integer(), nullable=True),
    sa.Column('end_event_id', sa.Integer(), nullable=True),
    sa.Column('prev_party_id', sa.Integer(), nullable=True),
    sa.Column('corr_typ_cd', sa.String(length=1), nullable=True),
    sa.Column('last_report_dt', sa.Date(), nullable=True),
    sa.Column('appointment_dt', sa.Date(), nullable=True),
    sa.Column('cessation_dt', sa.Date(), nullable=True),
    sa.Column('last_nme', sa.String(length=30), nullable=True),
    sa.Column('middle_nme', sa.String(length=30), nullable=True),
    sa.Column('first_nme', sa.String(length=30), nullable=True),
    sa.Column('business_nme', sa.String(length=150), nullable=True),
    sa.Column('bus_company_num', sa.String(length=15), nullable=True),
    sa.Column('email_address', sa.String(length=254), nullable=True),
    sa.Column('corp_party_seq_num', sa.Integer(), nullable=True),
    sa.Column('OFFICE_NOTIFICATION_DT', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('reason_typ_cd', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('corp_party_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CORP_PARTY')
    op.drop_table('CORPORATION')
    # ### end Alembic commands ###
