"""initial

Revision ID: 64b51387b13b
Revises: 
Create Date: 2020-01-28 00:53:46.288130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b51387b13b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CORPORATION',
    sa.Column('CORP_NUM', sa.String(length=10), nullable=False),
    sa.Column('CORP_FROZEN_TYP_CD', sa.String(length=1), nullable=True),
    sa.Column('CORP_TYP_CD', sa.String(length=3), nullable=True),
    sa.Column('RECOGNITION_DTS', sa.Date(), nullable=True),
    sa.Column('LAST_AR_FILED_DT', sa.Date(), nullable=True),
    sa.Column('TRANSITION_DT', sa.Date(), nullable=True),
    sa.Column('BN_9', sa.String(length=9), nullable=True),
    sa.Column('BN_15', sa.String(length=15), nullable=True),
    sa.Column('ACCESSION_NUM', sa.String(length=10), nullable=True),
    sa.Column('CORP_PASSWORD', sa.String(length=300), nullable=True),
    sa.Column('PROMPT_QUESTION', sa.String(length=100), nullable=True),
    sa.Column('ADMIN_EMAIL', sa.String(length=254), nullable=True),
    sa.Column('SEND_AR_IND', sa.String(length=1), nullable=True),
    sa.Column('TILMA_INVOLVED_IND', sa.String(length=1), nullable=True),
    sa.Column('TILMA_CESSATION_DT', sa.Date(), nullable=True),
    sa.Column('FIRM_LAST_IMAGE_DATE', sa.Date(), nullable=True),
    sa.Column('OS_SESSION', sa.Integer(), nullable=True),
    sa.Column('LAST_AGM_DATE', sa.Date(), nullable=True),
    sa.Column('FIRM_LP_XP_TERMINATION_DATE', sa.Date(), nullable=True),
    sa.Column('LAST_LEDGER_DT', sa.Date(), nullable=True),
    sa.Column('AR_REMINDER_OPTION', sa.String(length=10), nullable=True),
    sa.Column('AR_REMINDER_DATE', sa.String(length=20), nullable=True),
    sa.Column('TEMP_PASSWORD', sa.String(length=300), nullable=True),
    sa.Column('TEMP_PASSWORD_EXPIRY_DATE', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('CORP_NUM'),
    sa.UniqueConstraint('CORP_NUM')
    )
    op.create_table('CORP_PARTY',
    sa.Column('CORP_PARTY_ID', sa.Integer(), nullable=False),
    sa.Column('MAILING_ADDR_ID', sa.Integer(), nullable=True),
    sa.Column('DELIVERY_ADDR_ID', sa.Integer(), nullable=True),
    sa.Column('CORP_NUM', sa.String(length=10), nullable=True),
    sa.Column('PARTY_TYP_CD', sa.String(length=3), nullable=True),
    sa.Column('START_EVENT_ID', sa.Integer(), nullable=True),
    sa.Column('END_EVENT_ID', sa.Integer(), nullable=True),
    sa.Column('PREV_PARTY_ID', sa.Integer(), nullable=True),
    sa.Column('CORR_TYP_CD', sa.String(length=1), nullable=True),
    sa.Column('LAST_REPORT_DT', sa.Date(), nullable=True),
    sa.Column('APPOINTMENT_DT', sa.Date(), nullable=True),
    sa.Column('CESSATION_DT', sa.Date(), nullable=True),
    sa.Column('LAST_NME', sa.String(length=30), nullable=True),
    sa.Column('MIDDLE_NME', sa.String(length=30), nullable=True),
    sa.Column('FIRST_NME', sa.String(length=30), nullable=True),
    sa.Column('BUSINESS_NME', sa.String(length=150), nullable=True),
    sa.Column('BUS_COMPANY_NUM', sa.String(length=15), nullable=True),
    sa.Column('EMAIL_ADDRESS', sa.String(length=254), nullable=True),
    sa.Column('CORP_PARTY_SEQ_NUM', sa.Integer(), nullable=True),
    sa.Column('OFFICE_NOTIFICATION_DT', sa.Date(), nullable=True),
    sa.Column('PHONE', sa.String(length=30), nullable=True),
    sa.Column('REASON_TYP_CD', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('CORP_PARTY_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CORP_PARTY')
    op.drop_table('CORPORATION')
    # ### end Alembic commands ###
