"""empty message

Revision ID: 69f37ca73364
Revises: 64b51387b13b
Create Date: 2020-01-28 21:52:31.206932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f37ca73364'
down_revision = '64b51387b13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'CORPORATION', ['CORP_NUM'])
    op.drop_column('CORPORATION', 'PROMPT_QUESTION')
    op.drop_column('CORPORATION', 'TEMP_PASSWORD')
    op.drop_column('CORPORATION', 'TEMP_PASSWORD_EXPIRY_DATE')
    op.drop_column('CORPORATION', 'CORP_PASSWORD')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CORPORATION', sa.Column('CORP_PASSWORD', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('CORPORATION', sa.Column('TEMP_PASSWORD_EXPIRY_DATE', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('CORPORATION', sa.Column('TEMP_PASSWORD', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('CORPORATION', sa.Column('PROMPT_QUESTION', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'CORPORATION', type_='unique')
    # ### end Alembic commands ###
