"""empty message

Revision ID: 815af8fa93d8
Revises: eee6d70cf73f
Create Date: 2020-02-04 23:43:12.781212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815af8fa93d8'
down_revision = 'eee6d70cf73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OFFICER_TYPE',
    sa.Column('officer_typ_cd', sa.String(length=3), nullable=False),
    sa.Column('short_desc', sa.String(length=75), nullable=True),
    sa.Column('full_desc', sa.String(length=125), nullable=True),
    sa.PrimaryKeyConstraint('officer_typ_cd')
    )
    op.create_table('OFFICES_HELD',
    sa.Column('corp_party_id', sa.Integer(), nullable=False),
    sa.Column('officer_typ_cd', sa.String(length=3), nullable=False),
    sa.Column('dd_corp_party_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('corp_party_id', 'officer_typ_cd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OFFICES_HELD')
    op.drop_table('OFFICER_TYPE')
    # ### end Alembic commands ###
