"""empty message

Revision ID: 815af8fa93d8
Revises: eee6d70cf73f
Create Date: 2020-02-04 23:43:12.781212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815af8fa93d8'
down_revision = 'eee6d70cf73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OFFICER_TYPE',
    sa.Column('OFFICER_TYP_CD', sa.String(length=3), nullable=False),
    sa.Column('SHORT_DESC', sa.String(length=75), nullable=True),
    sa.Column('FULL_DESC', sa.String(length=125), nullable=True),
    sa.PrimaryKeyConstraint('OFFICER_TYP_CD')
    )
    op.create_table('OFFICES_HELD',
    sa.Column('CORP_PARTY_ID', sa.Integer(), nullable=False),
    sa.Column('OFFICER_TYP_CD', sa.String(length=3), nullable=False),
    sa.Column('DD_CORP_PARTY_ID', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CORP_PARTY_ID', 'OFFICER_TYP_CD')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OFFICES_HELD')
    op.drop_table('OFFICER_TYPE')
    # ### end Alembic commands ###
