"""empty message

Revision ID: dac0f0884105
Revises: 
Create Date: 2020-02-19 00:41:22.369450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac0f0884105'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema bc_registries")
    op.create_table('address',
    sa.Column('addr_id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('country_typ_cd', sa.String(length=2), nullable=True),
    sa.Column('postal_cd', sa.String(length=15), nullable=True),
    sa.Column('addr_line_1', sa.String(length=50), nullable=True),
    sa.Column('addr_line_2', sa.String(length=50), nullable=True),
    sa.Column('addr_line_3', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('address_format_type', sa.String(length=10), nullable=True),
    sa.Column('address_desc', sa.String(length=300), nullable=True),
    sa.Column('address_desc_short', sa.String(length=300), nullable=True),
    sa.Column('delivery_instructions', sa.String(length=80), nullable=True),
    sa.Column('unit_no', sa.String(length=6), nullable=True),
    sa.Column('unit_type', sa.String(length=10), nullable=True),
    sa.Column('civic_no', sa.String(length=6), nullable=True),
    sa.Column('civic_no_suffix', sa.String(length=10), nullable=True),
    sa.Column('street_name', sa.String(length=30), nullable=True),
    sa.Column('street_type', sa.String(length=10), nullable=True),
    sa.Column('street_direction', sa.String(length=10), nullable=True),
    sa.Column('lock_box_no', sa.String(length=5), nullable=True),
    sa.Column('installation_type', sa.String(length=10), nullable=True),
    sa.Column('installation_name', sa.String(length=30), nullable=True),
    sa.Column('installation_qualifier', sa.String(length=15), nullable=True),
    sa.Column('route_service_type', sa.String(length=10), nullable=True),
    sa.Column('route_service_no', sa.String(length=4), nullable=True),
    sa.Column('province_state_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('addr_id'),
    schema='bc_registries'
    )
    op.create_table('corp_name',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('corp_name_seq_num', sa.Integer(), nullable=True),
    sa.Column('corp_name_typ_cd', sa.String(length=2), nullable=True),
    sa.Column('start_event_id', sa.Integer(), nullable=True),
    sa.Column('end_event_id', sa.Integer(), nullable=True),
    sa.Column('srch_nme', sa.String(length=35), nullable=True),
    sa.Column('corp_nme', sa.String(length=150), nullable=True),
    sa.Column('dd_corp_num', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('corp_num'),
    schema='bc_registries'
    )
    op.create_table('corp_op_state',
    sa.Column('state_typ_cd', sa.String(length=3), nullable=False),
    sa.Column('op_state_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('short_desc', sa.String(length=15), nullable=True),
    sa.Column('full_desc', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('state_typ_cd'),
    schema='bc_registries'
    )
    op.create_table('corp_party',
    sa.Column('corp_party_id', sa.Integer(), nullable=False),
    sa.Column('mailing_addr_id', sa.Integer(), nullable=True),
    sa.Column('delivery_addr_id', sa.Integer(), nullable=True),
    sa.Column('corp_num', sa.String(length=10), nullable=True),
    sa.Column('party_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('start_event_id', sa.Integer(), nullable=True),
    sa.Column('end_event_id', sa.Integer(), nullable=True),
    sa.Column('prev_party_id', sa.Integer(), nullable=True),
    sa.Column('corr_typ_cd', sa.String(length=1), nullable=True),
    sa.Column('last_report_dt', sa.Date(), nullable=True),
    sa.Column('appointment_dt', sa.Date(), nullable=True),
    sa.Column('cessation_dt', sa.Date(), nullable=True),
    sa.Column('last_nme', sa.String(length=30), nullable=True),
    sa.Column('middle_nme', sa.String(length=30), nullable=True),
    sa.Column('first_nme', sa.String(length=30), nullable=True),
    sa.Column('business_nme', sa.String(length=150), nullable=True),
    sa.Column('bus_company_num', sa.String(length=15), nullable=True),
    sa.Column('email_address', sa.String(length=254), nullable=True),
    sa.Column('corp_party_seq_num', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('reason_typ_cd', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('corp_party_id'),
    schema='bc_registries'
    )
    op.create_table('corp_state',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('start_event_id', sa.Integer(), nullable=False),
    sa.Column('end_event_id', sa.Integer(), nullable=True),
    sa.Column('state_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('dd_corp_num', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('corp_num', 'start_event_id'),
    schema='bc_registries'
    )
    op.create_table('corporation',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('corp_frozen_typ_cd', sa.String(length=1), nullable=True),
    sa.Column('corp_typ_cd', sa.String(length=3), nullable=True),
    sa.Column('recognition_dts', sa.Date(), nullable=True),
    sa.Column('last_ar_filed_dt', sa.Date(), nullable=True),
    sa.Column('transition_dt', sa.Date(), nullable=True),
    sa.Column('bn_9', sa.String(length=9), nullable=True),
    sa.Column('bn_15', sa.String(length=15), nullable=True),
    sa.Column('accession_num', sa.String(length=10), nullable=True),
    sa.Column('admin_email', sa.String(length=254), nullable=True),
    sa.Column('send_ar_ind', sa.String(length=1), nullable=True),
    sa.Column('tilma_involved_ind', sa.String(length=1), nullable=True),
    sa.Column('tilma_cessation_dt', sa.Date(), nullable=True),
    sa.Column('firm_last_image_date', sa.Date(), nullable=True),
    sa.Column('os_session', sa.Integer(), nullable=True),
    sa.Column('last_agm_date', sa.Date(), nullable=True),
    sa.Column('firm_lp_xp_termination_date', sa.Date(), nullable=True),
    sa.Column('last_ledger_dt', sa.Date(), nullable=True),
    sa.Column('ar_reminder_option', sa.String(length=10), nullable=True),
    sa.Column('ar_reminder_date', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('corp_num'),
    sa.UniqueConstraint('corp_num'),
    schema='bc_registries'
    )
    op.create_table('office',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('office_typ_cd', sa.String(length=2), nullable=False),
    sa.Column('start_event_id', sa.Integer(), nullable=False),
    sa.Column('end_event_id', sa.Integer(), nullable=True),
    sa.Column('mailing_addr_id', sa.Integer(), nullable=True),
    sa.Column('delivery_addr_id', sa.Integer(), nullable=True),
    sa.Column('dd_corp_num', sa.String(length=10), nullable=True),
    sa.Column('email_address', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('corp_num', 'office_typ_cd', 'start_event_id'),
    schema='bc_registries'
    )
    op.create_table('office_type',
    sa.Column('office_typ_cd', sa.String(length=2), nullable=False),
    sa.Column('short_desc', sa.String(length=15), nullable=True),
    sa.Column('full_desc', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('office_typ_cd'),
    schema='bc_registries'
    )
    op.create_table('officer_type',
    sa.Column('officer_typ_cd', sa.String(length=3), nullable=False),
    sa.Column('short_desc', sa.String(length=75), nullable=True),
    sa.Column('full_desc', sa.String(length=125), nullable=True),
    sa.PrimaryKeyConstraint('officer_typ_cd'),
    schema='bc_registries'
    )
    op.create_table('offices_held',
    sa.Column('corp_party_id', sa.Integer(), nullable=False),
    sa.Column('officer_typ_cd', sa.String(length=3), nullable=False),
    sa.Column('dd_corp_party_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('corp_party_id', 'officer_typ_cd'),
    schema='bc_registries'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offices_held', schema='bc_registries')
    op.drop_table('officer_type', schema='bc_registries')
    op.drop_table('office_type', schema='bc_registries')
    op.drop_table('office', schema='bc_registries')
    op.drop_table('corporation', schema='bc_registries')
    op.drop_table('corp_state', schema='bc_registries')
    op.drop_table('corp_party', schema='bc_registries')
    op.drop_table('corp_op_state', schema='bc_registries')
    op.drop_table('corp_name', schema='bc_registries')
    op.drop_table('address', schema='bc_registries')
    # ### end Alembic commands ###
