"""empty message

Revision ID: e28650fff8d2
Revises: 97734424aa05
Create Date: 2020-03-20 01:45:02.192329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28650fff8d2'
down_revision = '97734424aa05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('filing_typ_cd', sa.String(length=5), nullable=True),
    sa.Column('effective_dt', sa.Date(), nullable=True),
    sa.Column('change_dt', sa.Date(), nullable=True),
    sa.Column('registration_dt', sa.Date(), nullable=True),
    sa.Column('period_end_dt', sa.Date(), nullable=True),
    sa.Column('accession_num', sa.String(length=10), nullable=True),
    sa.Column('arrangement_ind', sa.String(length=1), nullable=True),
    sa.Column('auth_sign_dt', sa.Date(), nullable=True),
    sa.Column('withdrawn_event_id', sa.Integer(), nullable=True),
    sa.Column('ods_typ_cd', sa.String(length=2), nullable=True),
    sa.Column('dd_event_id', sa.Integer(), nullable=True),
    sa.Column('access_cd', sa.String(length=9), nullable=True),
    sa.Column('nr_num', sa.String(length=10), nullable=True),
    sa.Column('court_appr_ind', sa.String(length=1), nullable=True),
    sa.Column('court_order_num', sa.String(length=255), nullable=True),
    sa.Column('agm_date', sa.Date(), nullable=True),
    sa.Column('new_corp_num', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('filing_type',
    sa.Column('filing_typ_cd', sa.String(length=5), nullable=False),
    sa.Column('filing_typ_class', sa.String(length=10), nullable=True),
    sa.Column('short_desc', sa.String(length=50), nullable=True),
    sa.Column('full_desc', sa.String(length=125), nullable=True),
    sa.PrimaryKeyConstraint('filing_typ_cd')
    )
    op.create_unique_constraint(None, 'corporation', ['corp_num'])
    op.create_unique_constraint(None, 'event', ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_constraint(None, 'corporation', type_='unique')
    op.drop_table('filing_type')
    op.drop_table('filing')
    # ### end Alembic commands ###
