"""empty message

Revision ID: e4d106926f51
Revises: 815af8fa93d8
Create Date: 2020-02-15 20:17:27.009847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d106926f51'
down_revision = '815af8fa93d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OFFICE',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('OFFICE_TYP_CD', sa.String(length=2), nullable=False),
    sa.Column('START_EVENT_ID', sa.Integer(), nullable=False),
    sa.Column('END_EVENT_ID', sa.Integer(), nullable=True),
    sa.Column('MAILING_ADDR_ID', sa.Integer(), nullable=True),
    sa.Column('DELIVERY_ADDR_ID', sa.Integer(), nullable=True),
    sa.Column('DD_CORP_NUM', sa.String(length=10), nullable=True),
    sa.Column('EMAIL_ADDRESS', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('corp_num', 'OFFICE_TYP_CD', 'START_EVENT_ID')
    )
    op.create_table('OFFICE_TYPE',
    sa.Column('OFFICE_TYP_CD', sa.String(length=2), nullable=False),
    sa.Column('SHORT_DESC', sa.String(length=15), nullable=True),
    sa.Column('FULL_DESC', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('OFFICE_TYP_CD')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OFFICE_TYPE')
    op.drop_table('OFFICE')
    # ### end Alembic commands ###
