"""empty message

Revision ID: e4d106926f51
Revises: 815af8fa93d8
Create Date: 2020-02-15 20:17:27.009847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d106926f51'
down_revision = '815af8fa93d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OFFICE',
    sa.Column('corp_num', sa.String(length=10), nullable=False),
    sa.Column('office_typ_cd', sa.String(length=2), nullable=False),
    sa.Column('start_event_id', sa.Integer(), nullable=False),
    sa.Column('end_event_id', sa.Integer(), nullable=True),
    sa.Column('mailing_addr_id', sa.Integer(), nullable=True),
    sa.Column('delivery_addr_id', sa.Integer(), nullable=True),
    sa.Column('dd_corp_num', sa.String(length=10), nullable=True),
    sa.Column('email_address', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('corp_num', 'office_typ_cd', 'start_event_id')
    )
    op.create_table('OFFICE_TYPE',
    sa.Column('office_typ_cd', sa.String(length=2), nullable=False),
    sa.Column('short_desc', sa.String(length=15), nullable=True),
    sa.Column('full_desc', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('office_typ_cd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OFFICE_TYPE')
    op.drop_table('OFFICE')
    # ### end Alembic commands ###
