"""empty message

Revision ID: eee6d70cf73f
Revises: 189beb42cff3
Create Date: 2020-02-04 08:40:01.848412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee6d70cf73f'
down_revision = '189beb42cff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADDRESS',
    sa.Column('addr_id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('country_typ_cd', sa.String(length=2), nullable=True),
    sa.Column('postal_cd', sa.String(length=15), nullable=True),
    sa.Column('addr_line_1', sa.String(length=50), nullable=True),
    sa.Column('addr_line_2', sa.String(length=50), nullable=True),
    sa.Column('addr_line_3', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=40), nullable=True),
    sa.Column('address_format_type', sa.String(length=10), nullable=True),
    sa.Column('address_desc', sa.String(length=300), nullable=True),
    sa.Column('address_desc_short', sa.String(length=300), nullable=True),
    sa.Column('delivery_instructions', sa.String(length=80), nullable=True),
    sa.Column('unit_no', sa.String(length=6), nullable=True),
    sa.Column('unit_type', sa.String(length=10), nullable=True),
    sa.Column('civic_no', sa.String(length=6), nullable=True),
    sa.Column('civic_no_suffix', sa.String(length=10), nullable=True),
    sa.Column('street_name', sa.String(length=30), nullable=True),
    sa.Column('street_type', sa.String(length=10), nullable=True),
    sa.Column('street_direction', sa.String(length=10), nullable=True),
    sa.Column('lock_box_no', sa.String(length=5), nullable=True),
    sa.Column('installation_type', sa.String(length=10), nullable=True),
    sa.Column('installation_name', sa.String(length=30), nullable=True),
    sa.Column('installation_qualifier', sa.String(length=15), nullable=True),
    sa.Column('route_service_type', sa.String(length=10), nullable=True),
    sa.Column('route_service_no', sa.String(length=4), nullable=True),
    sa.Column('province_state_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('addr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ADDRESS')
    # ### end Alembic commands ###
