"""empty message

Revision ID: eee6d70cf73f
Revises: 189beb42cff3
Create Date: 2020-02-04 08:40:01.848412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee6d70cf73f'
down_revision = '189beb42cff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADDRESS',
    sa.Column('ADDR_ID', sa.Integer(), nullable=False),
    sa.Column('PROVINCE', sa.String(length=2), nullable=True),
    sa.Column('COUNTRY_TYP_CD', sa.String(length=2), nullable=True),
    sa.Column('POSTAL_CD', sa.String(length=15), nullable=True),
    sa.Column('ADDR_LINE_1', sa.String(length=50), nullable=True),
    sa.Column('ADDR_LINE_2', sa.String(length=50), nullable=True),
    sa.Column('ADDR_LINE_3', sa.String(length=50), nullable=True),
    sa.Column('CITY', sa.String(length=40), nullable=True),
    sa.Column('ADDRESS_FORMAT_TYPE', sa.String(length=10), nullable=True),
    sa.Column('ADDRESS_DESC', sa.String(length=300), nullable=True),
    sa.Column('ADDRESS_DESC_SHORT', sa.String(length=300), nullable=True),
    sa.Column('DELIVERY_INSTRUCTIONS', sa.String(length=80), nullable=True),
    sa.Column('UNIT_NO', sa.String(length=6), nullable=True),
    sa.Column('UNIT_TYPE', sa.String(length=10), nullable=True),
    sa.Column('CIVIC_NO', sa.String(length=6), nullable=True),
    sa.Column('CIVIC_NO_SUFFIX', sa.String(length=10), nullable=True),
    sa.Column('STREET_NAME', sa.String(length=30), nullable=True),
    sa.Column('STREET_TYPE', sa.String(length=10), nullable=True),
    sa.Column('STREET_DIRECTION', sa.String(length=10), nullable=True),
    sa.Column('LOCK_BOX_NO', sa.String(length=5), nullable=True),
    sa.Column('INSTALLATION_TYPE', sa.String(length=10), nullable=True),
    sa.Column('INSTALLATION_NAME', sa.String(length=30), nullable=True),
    sa.Column('INSTALLATION_QUALIFIER', sa.String(length=15), nullable=True),
    sa.Column('ROUTE_SERVICE_TYPE', sa.String(length=10), nullable=True),
    sa.Column('ROUTE_SERVICE_NO', sa.String(length=4), nullable=True),
    sa.Column('PROVINCE_STATE_NAME', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('ADDR_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ADDRESS')
    # ### end Alembic commands ###
