'''empty message

Revision ID: f1714b3e3bfa
Revises: e28650fff8d2
Create Date: 2020-04-14 18:27:49.349718

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1714b3e3bfa'
down_revision = 'e28650fff8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nickname',
    sa.Column('name_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    #op.drop_table('office_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('office_type',
    # sa.Column('office_typ_cd', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    # sa.Column('short_desc', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    # sa.Column('full_desc', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('office_typ_cd', name='office_type_pkey')
    # )
    op.drop_table('nickname')
    # ### end Alembic commands ###
